#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

apt install software-properties-common -y
add-apt-repository universe
add-apt-repository ppa:certbot/certbot
apt update

apt install certbot -y

certbot certonly --standalone

tagScript success

exit 0
