#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

domainName="${CWM_SERVERIP//./-}.cloud-xip.io"

echo "Opening port 80 for letsencrypt" | log
ufw allow http

echo "Installing certbot" | log
apt install software-properties-common -y
add-apt-repository universe
add-apt-repository ppa:certbot/certbot
apt update
apt install certbot -y
checkPackageInstalled certbot

echo "Retrieving SSL domain certification" | log
certbot certonly -n --standalone --preferred-challenges http --agree-tos --email ${ADMINEMAIL} -d ${domainName} --dry-run
waitOrStop 0

tagScript success

exit 0