#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

domainName="${CWM_SERVERIP//./-}.cloud-xip.io"

echo "Opening port 80 for letsencrypt" | log
ufw allow http

echo "Retrieving SSL domain certification" | log
certbot certonly -n --standalone --preferred-challenges http --agree-tos --email ${ADMINEMAIL} -d ${domainName} --dry-run
waitOrStop 0

tag ssl-ready.success
tagScript success

exit 0