#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

domainName="${CWM_SERVERIP//./-}.cloud-xip.io"

ok=1
n=0
until [ $n -ge 3 ]; do

    if certbot certonly -n --standalone --preferred-challenges http --agree-tos --email ${ADMINEMAIL} -d ${domainName} --test-cert | grep -q -E '(fail|error|not )'; then

        n=$[$n+1]
        sleep 3

    else

        $ok=0
        break

    fi

done

waitOrStop $ok

tagScript success

exit 0