#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success
rootDir=$(rootDir)
domainName="${CWM_SERVERIP//./-}.cloud-xip.io"

echo "Enabling certbot for machine" | log
mkdir -p /var/lib/letsencrypt/.well-known
chgrp www-data /var/lib/letsencrypt
chmod g+s /var/lib/letsencrypt

echo "Preparing nginx for certbot certification" | log
cp $rootDir/tweaks/letsencrypt-nginx-route.conf /etc/nginx/snippets/
cp $rootDir/tweaks/letsencrypt-nginx-register.conf /etc/nginx/sites-available/
ln -s /etc/nginx/sites-available/letsencrypt-nginx-register.conf /etc/nginx/sites-enabled/
systemctl restart nginx.service
waitOrStop 0

echo "Generating letsencrypt certificates with certbot" | log
certbot certonly --agree-tos -n --email ${ADMINEMAIL} --webroot -w /var/lib/letsencrypt/ -d ${domainName}
waitOrStop 0
unlink /etc/nginx/sites-enabled/letsencrypt-nginx-register.conf
# remove default vhosts
unlink /etc/nginx/sites-enabled/default

echo "Attaching certificates to nginx configuration" | log
cp $rootDir/tweaks/letsencrypt-nginx-certs.conf /etc/nginx/snippets/
certsPath=/etc/nginx/snippets/letsencrypt-nginx-certs.conf
sed -i "s|/path/to/your.key|/etc/letsencrypt/live/${domainName}/privkey.pem|" $certsPath
sed -i "s|/path/to/your.crt|/etc/letsencrypt/live/${domainName}/fullchain.pem|" $certsPath
sed -i "s|/path/to/your.chain|/etc/letsencrypt/live/${domainName}/chain.pem|" $certsPath

echo "Creating an SSL vhost" | log
cat << EOF >> /etc/nginx/sites-available/default-ssl
server {
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;
	
	server_name _;

	include snippets/letsencrypt-nginx-certs.conf;
	include snippets/letsencrypt-nginx-route.conf;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	location / {
		# Default Location
	}
}
EOF

echo "Symlink to sites-enabled" | log 
ln -s /etc/nginx/sites-available/default-ssl /etc/nginx/sites-enabled/

echo "Restart NGINX service" | log
systemctl restart nginx.service
waitOrStop 0

descriptionAppend "SSL certificates location: /etc/letsencrypt/live/${domainName}/"
descriptionAppend " "

tag ssl-ready.success
tagScript success

exit 0
