#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)
hostname=$(echo ${SERVERIP//./-} | awk '{ print "vesta."$1".cloud-xip.io"}')

echo "Running VestaCP Official Installer" | log
curlDownload http://vestacp.com/pub/vst-install.sh
waitOrStop 0
bash vst-install.sh --nginx yes --phpfpm yes --apache no --named yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota no --exim yes --dovecot yes --spamassassin yes --clamav yes --softaculous yes --mysql yes --postgresql no --interactive no --password ${ADMINPASSWORD} --email ${ADMINEMAIL} --hostname ${hostname} | log
waitOrStop 0

echo "Adding descriptions" | log
descriptionAppend "VestaCP Address: https://${hostname}:8083"
descriptionAppend "VestaCP user: admin"
descriptionAppend "VestaCP password: ${ADMINPASSWORD}"
descriptionAppend " "

tagScript success

exit 0
